define(
    {
        "movieList": [{
            "id": 344328,
            "haspromotionTag": false,
            "img": "http://p0.meituan.net/w.h/movie/47af2656af6cd0110057bc527b862c665484423.jpg",
            "version": "v3d imax",
            "nm": "X-Men: Black Phoenix",
            "preShow": false,
            "sc": 0,
            "globalReleased": true,
            "wish": 307488,
            "star": "Sophie Turner, James McAvoy, Michael Fassbinder",
            "rt": "2019-06-06",
            "showInfo": "Today's 264 theaters show 3,973 games",
            "showst": 3,
            "wishst": 0
        }, {
            "id": 1218215,
            "haspromotionTag": false,
            "img": "http://p0.meituan.net/w.h/movie/c0a02897fa49e5c529bfe3cead0f49652270427.jpg",
            "version": "v2d imax",
            "nm": "Chasing Dragon II",
            "preShow": false,
            "sc": 0,
            "globalReleased": true,
            "wish": 137664,
            "star": "梁家辉,古天乐,林家栋",
            "rt": "2019-06-06",
            "showInfo": "Today's 264 theaters show 3108 games",
            "showst": 3,
            "wishst": 0
        }, {
            "id": 246061,
            "haspromotionTag": false,
            "img": "http://p0.meituan.net/w.h/movie/71fba05fbe4912cb70d27b87c3c856393364925.jpg",
            "version": "v3d imax",
            "nm": "Godzilla 2: The King of Monsters",
            "preShow": false,
            "sc": 8.5,
            "globalReleased": true,
            "wish": 325416,
            "star": "Kyle Chandler, Vera Famega, Millie Bobby Brown",
            "rt": "2019-05-31",
            "showInfo": "Today 256 theaters show 1268 games",
            "showst": 3,
            "wishst": 0
        }, {
            "id": 887623,
            "haspromotionTag": false,
            "img": "http://p0.meituan.net/w.h/movie/36b245c374ec10f6aba4d337f78e97f12022575.jpg",
            "version": "",
            "nm": "I can't do anything",
            "preShow": false,
            "sc": 9.3,
            "globalReleased": true,
            "wish": 16047,
            "star": "Hernick Rosshan, Yami Goldham, Lonette Roy",
            "rt": "2019-06-05",
            "showInfo": "Today 229 theaters show 762 games",
            "showst": 3,
            "wishst": 0
        }, {
            "id": 1242431,
            "haspromotionTag": false,
            "img": "http://p0.meituan.net/w.h/movie/b6e77d67efdc6ac89a52b956ead366ae5785152.jpg",
            "version": "",
            "nm": "The best of us",
            "preShow": false,
            "sc": 0,
            "globalReleased": false,
            "wish": 122838,
            "star": "Chen Feiyu, He Lanjiao, Hui Yinghong",
            "rt": "2019-06-06",
            "showInfo": "Today 238 theaters show 667 games",
            "showst": 3,
            "wishst": 0
        }, {
            "id": 1207959,
            "haspromotionTag": false,
            "img": "http://p1.meituan.net/w.h/moviemachine/42ef79dd1d894b67dd57de383d753c03556009.jpg",
            "version": "v3d imax",
            "nm": "Aladdin",
            "preShow": false,
            "sc": 9,
            "globalReleased": true,
            "wish": 48343,
            "star": "Mena Masood, Naomi Scott, Marwan Kenzari",
            "rt": "2019-05-24",
            "showInfo": "There are 192 theaters in 97 theaters today",
            "showst": 3,
            "wishst": 0
        }, {
            "id": 1226516,
            "haspromotionTag": false,
            "img": "http://p1.meituan.net/w.h/movie/06daf32301ff2fd54f6ffd59299d0326672524.jpg",
            "version": "",
            "nm": "Doraemon: Daxiong's Moon Adventure",
            "preShow": false,
            "sc": 8.7,
            "globalReleased": true,
            "wish": 59726,
            "star": "Iwata isabi, Ohara Emi, Jiamei Yumei",
            "rt": "2019-06-01",
            "showInfo": "Today 151 theaters show 152 games",
            "showst": 3,
            "wishst": 0
        }, {
            "id": 1279725,
            "haspromotionTag": false,
            "img": "http://p1.meituan.net/w.h/movie/424353b8357c51d3a1f6dba24f5cac871330276.jpg",
            "version": "",
            "nm": "When we are wide open",
            "preShow": false,
            "sc": 0,
            "globalReleased": true,
            "wish": 3949,
            "star": "Liu Qiushi, Liu Yuchang, He Ruyan",
            "rt": "2019-06-06",
            "showInfo": "107 theaters are shown in 41 theaters today",
            "showst": 3,
            "wishst": 0
        }, {
            "id": 346629,
            "haspromotionTag": false,
            "img": "http://p0.meituan.net/w.h/movie/f29c0f9ff0340d00085f4bc1a395ecf02603950.jpg",
            "version": "v3d imax",
            "nm": "Great Detective Pikachu",
            "preShow": false,
            "sc": 8.5,
            "globalReleased": true,
            "wish": 280645,
            "star": "Ryan Reynolds, Justis Smith, Catherine Newton",
            "rt": "2019-05-10",
            "showInfo": "49 theaters are shown in 37 theaters today",
            "showst": 3,
            "wishst": 0
        }, {
            "id": 1207185,
            "haspromotionTag": false,
            "img": "http://p0.meituan.net/w.h/movie/313ed0afcdb4d1cc37cd12b402e9e4421137394.jpg",
            "version": "",
            "nm": "Qin Ming·Life and Death",
            "preShow": false,
            "sc": 0,
            "globalReleased": false,
            "wish": 78190,
            "star": "Yan Yukuan, Dais, Yule",
            "rt": "2019-06-14",
            "showInfo": "2019-06-14 released next Friday",
            "showst": 4,
            "wishst": 0
        }, {
            "id": 1218727,
            "haspromotionTag": false,
            "img": "http://p1.meituan.net/w.h/movie/d28b729ffe72353a72d1e7ef8a9b90591544978.jpg",
            "version": "",
            "nm": "What is home?",
            "preShow": false,
            "sc": 9.3,
            "globalReleased": true,
            "wish": 101827,
            "star": "Zane Al Rafia, Jodanos Hifero, Boluvatif Trej Banker",
            "rt": "2019-04-29",
            "showInfo": "Today 21 theaters show 21 games",
            "showst": 3,
            "wishst": 0
        }]
    }
)